# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: TestSpace Coverage 

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/ruby_3_1.gemfile

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install Appraisal Gems
        run: bundle exec rake install

      - name: Run tests
        run: FOR_TESTSPACE=true bundle exec rake latest

      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}
      - name: Push result to TestSpace server
        run: |
          testspace ./coverage/coverage.xml
        if: always()

